// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api_format.proto

package parts2plans

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Part struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Qty                  int32    `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Part) Reset()         { *m = Part{} }
func (m *Part) String() string { return proto.CompactTextString(m) }
func (*Part) ProtoMessage()    {}
func (*Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1cc40e6f5d1cb9, []int{0}
}

func (m *Part) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Part.Unmarshal(m, b)
}
func (m *Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Part.Marshal(b, m, deterministic)
}
func (m *Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Part.Merge(m, src)
}
func (m *Part) XXX_Size() int {
	return xxx_messageInfo_Part.Size(m)
}
func (m *Part) XXX_DiscardUnknown() {
	xxx_messageInfo_Part.DiscardUnknown(m)
}

var xxx_messageInfo_Part proto.InternalMessageInfo

func (m *Part) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Part) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Part) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Part) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

type PartList struct {
	Parts                []*Part  `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartList) Reset()         { *m = PartList{} }
func (m *PartList) String() string { return proto.CompactTextString(m) }
func (*PartList) ProtoMessage()    {}
func (*PartList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1cc40e6f5d1cb9, []int{1}
}

func (m *PartList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartList.Unmarshal(m, b)
}
func (m *PartList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartList.Marshal(b, m, deterministic)
}
func (m *PartList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartList.Merge(m, src)
}
func (m *PartList) XXX_Size() int {
	return xxx_messageInfo_PartList.Size(m)
}
func (m *PartList) XXX_DiscardUnknown() {
	xxx_messageInfo_PartList.DiscardUnknown(m)
}

var xxx_messageInfo_PartList proto.InternalMessageInfo

func (m *PartList) GetParts() []*Part {
	if m != nil {
		return m.Parts
	}
	return nil
}

type Project struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string    `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	ImagePath            string    `protobuf:"bytes,4,opt,name=imagePath,proto3" json:"imagePath,omitempty"`
	PartsList            *PartList `protobuf:"bytes,5,opt,name=partsList,proto3" json:"partsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1cc40e6f5d1cb9, []int{2}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Project) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *Project) GetPartsList() *PartList {
	if m != nil {
		return m.PartsList
	}
	return nil
}

type ProjectList struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjectList) Reset()         { *m = ProjectList{} }
func (m *ProjectList) String() string { return proto.CompactTextString(m) }
func (*ProjectList) ProtoMessage()    {}
func (*ProjectList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1cc40e6f5d1cb9, []int{3}
}

func (m *ProjectList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectList.Unmarshal(m, b)
}
func (m *ProjectList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectList.Marshal(b, m, deterministic)
}
func (m *ProjectList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectList.Merge(m, src)
}
func (m *ProjectList) XXX_Size() int {
	return xxx_messageInfo_ProjectList.Size(m)
}
func (m *ProjectList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectList.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectList proto.InternalMessageInfo

func (m *ProjectList) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*Part)(nil), "parts2plans.Part")
	proto.RegisterType((*PartList)(nil), "parts2plans.PartList")
	proto.RegisterType((*Project)(nil), "parts2plans.Project")
	proto.RegisterType((*ProjectList)(nil), "parts2plans.ProjectList")
}

func init() { proto.RegisterFile("api_format.proto", fileDescriptor_2c1cc40e6f5d1cb9) }

var fileDescriptor_2c1cc40e6f5d1cb9 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0x4b, 0x4e, 0x04, 0x21,
	0x14, 0x0c, 0xfd, 0xd1, 0xe9, 0xd7, 0x89, 0x19, 0x89, 0x26, 0x2c, 0x5c, 0x74, 0xd8, 0xc8, 0xaa,
	0x63, 0xba, 0x0f, 0xe0, 0x05, 0x5c, 0x10, 0x2e, 0x60, 0x9e, 0xd3, 0xa8, 0x18, 0x7b, 0x40, 0x60,
	0xe3, 0x3d, 0x3c, 0xb0, 0x01, 0xd4, 0xd1, 0xb8, 0x9b, 0x5d, 0x51, 0x55, 0xbc, 0xaa, 0xf7, 0x60,
	0x8b, 0xce, 0xdc, 0x3f, 0x5a, 0xbf, 0x62, 0x1c, 0x9d, 0xb7, 0xd1, 0xd2, 0xde, 0xa1, 0x8f, 0x61,
	0x72, 0xaf, 0xb8, 0x0f, 0x5c, 0x42, 0x23, 0xd1, 0x47, 0x7a, 0x06, 0x95, 0x59, 0x18, 0x19, 0x88,
	0x68, 0x55, 0x65, 0x16, 0x4a, 0xa1, 0xd9, 0xe3, 0xaa, 0x59, 0x35, 0x10, 0xd1, 0xa9, 0x8c, 0x13,
	0xb7, 0xe8, 0xb0, 0x63, 0x75, 0xe1, 0x12, 0xa6, 0x5b, 0xa8, 0xdf, 0xe2, 0x3b, 0x6b, 0xf2, 0xc7,
	0x04, 0xf9, 0x0c, 0x9b, 0x34, 0xf1, 0xce, 0x84, 0x48, 0xaf, 0xa1, 0xcd, 0x61, 0x8c, 0x0c, 0xb5,
	0xe8, 0xa7, 0xf3, 0xf1, 0x57, 0xf4, 0x98, 0x5c, 0xaa, 0xe8, 0xfc, 0x83, 0xc0, 0xa9, 0xf4, 0xf6,
	0x45, 0xef, 0x8e, 0xaf, 0x72, 0x05, 0x9d, 0x59, 0xf1, 0x49, 0x4b, 0x8c, 0xcf, 0xb9, 0x50, 0xa7,
	0x0e, 0x04, 0x9d, 0xa1, 0xcb, 0x51, 0xa9, 0x17, 0x6b, 0x07, 0x22, 0xfa, 0xe9, 0xf2, 0x5f, 0x9d,
	0x24, 0xaa, 0x83, 0x8f, 0xdf, 0x42, 0xff, 0xd5, 0x2a, 0xaf, 0x73, 0x03, 0x1b, 0x57, 0x9e, 0xdf,
	0x1b, 0x5d, 0xfc, 0x1d, 0x51, 0x44, 0xf5, 0xe3, 0x7a, 0x38, 0xc9, 0x27, 0x9f, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x8d, 0x83, 0x0b, 0x86, 0x01, 0x00, 0x00,
}
